name: Cipher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install Dependencies
      run: |
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Lint with ruff
      run: |
        ruff check .
    - name: Lint with bandit
      run: |
        bandit -r src
    - name: Run Safety
      run: |
        safety check
      continue-on-error: true
    - name: Run Pytest
      run: |
        coverage run -m pytest tests
        coverage report
        coverage xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
